# To change this license header, choose License Headers in Project Properties.
# To change this template file, choose Tools | Templates
# and open the template in the editor.
#FROM payara/micro:latest
FROM jboss/wildfly
#ENV COPY_TMP /opt/dockersrc
#RUN mkdir -p $COPY_TMP

ADD standalone-custom.xml /opt/wildfly/standalone/configuration/
ADD FitnessCRM-*.war /opt/jboss/wildfly/standalone/deployments/
CMD ["/opt/wildfly/bin/standalone.sh", "-c", "standalone-custom.xml", "-b", "0.0.0.0", "-bmanagement", "0.0.0.0"]




#COPY ./FitnessCRM-*.war /opt/payara/deployments/
#COPY /target/FitnessCRM-* /opt/payara/deployments/
#COPY ./domain-fitnessCRM.xml $COPY_TMP
#COPY /domain-fitnessCRM.xml /opt/payara/

#USER root
#RUN chown -R payara:payara /opt/payara/domain-fitnessCRM.xml
#RUN chmod -R 664 /opt/payara/domain-fitnessCRM.xml
#RUN chown -R payara:payara /opt/payara/deployments/FitnessCRM-*.war
#RUN chmod -R 664 /opt/payara/deployments/FitnessCRM-*.war

#USER payara
#RUN mv /dockersrc/* /opt/payara/deployments/ &&\  
 #   chmod  777 /opt/payara/deployments/FitnessCRM-5.4.4.war /opt/payara/deployments/domain-fitnessCRM.xml

#CMD ["java","-jar","/opt/payara/payara-micro.jar","--deploymentDir","/opt/payara/deployments","--domainconfig","/opt/payara/domain-fitnessCRM.xml"]

#CMD ["java","-jar","/opt/payara/payara-micro.jar","--deploymentDir","/opt/payara/deployments"]